### ISSUE TITLE
Javascript dependencies needs an update - tiptap 2 update ahead

### ISSUE THREAD

**Issue by jonassiewertsen** [xndbogdan/statamic-bard-text-color#10]
Dear @xndbogdan 

We are working on updating tiptap to version 2: https://github.com/statamic/cms/pull/6043

As this might break your addon, we are willing to help updating it. 

**Could you update the Javascript dependencies?**
If you got time and are willing to update javascript dependencies, we will help updating this addon, so it works with tiptap 2.

**Comment by xndbogdan** [comment]
Sure. 
I think I got some time this weekend to patch it up 😅

**Comment by xndbogdan** [comment]
https://github.com/xndbogdan/statamic-bard-text-color/tree/feature/update-tiptap
This is WIP but should work with tiptap2

**Comment by xndbogdan** [comment]
Released V3.0 of this package
It's now compatible with statamic 3.4
