### ISSUE TITLE
Can't config custom colors

### ISSUE THREAD

**Issue by remiduval** [xndbogdan/statamic-bard-text-color#15]
Hey!

Since the last update, overriding colors through the config file doesn't work on my side. Here's what I have on my `config/bard-custom-colors.php`

```
    'custom_colors' => [
    ],

    'default_colors' => [
        'Green'     => '#008000',
        'Blue'      => '#2574A9',
        'Pink'      => '#B500B5',
        'Purple'    => '#58007E',
        'Yellow'    => '#8D6708',
        'Orange'    => '#D43900',
        'Red'       => '#AA0000'
    ],
```

**Comment by xndbogdan** [comment]
Hi. 
Thanks for reporting this issue.
Which version are you using?
You're on 2.3, correct?
I'll investigate as soon as possible and come up with a fix.

**Comment by remiduval** [comment]
Hi!
I'm on 2.3 indeed! Thanks

**Comment by xndbogdan** [comment]
Hi!
Please update to version 2.4.
The issue should be fixed but I'll need your confirmation.

**Comment by xndbogdan** [comment]
I'm closing this issue.
If there's further problems, open up a new one.

**Comment by remiduval** [comment]
It works again with 2.4, thank you!
