### ISSUE TITLE
No colors to select

### ISSUE THREAD

**Issue by frankroc2022** [xndbogdan/statamic-bard-text-color#18]
I edited the bard-custom-colors.php in vendor/xndbogdan/statamic-bard-text-color/config/ but I can't select colors neither Default nor Custom. This is important for me.

Not so important but interesting, how to get the tailwind colors?

**Comment by xndbogdan** [comment]
Hi.
Can you try creating the file in your application config folder?
I'll investigate this issue as soon as possible.

**Comment by xndbogdan** [comment]
Issue was fixed
Sorry for fixing it so late 😅
