### ISSUE TITLE
color issues

### ISSUE THREAD

**Issue by Oleafeon** [xndbogdan/statamic-bard-text-color#19]
when we add the color white to the options the text in the editor becomes white which makes it hard to read for the customer is there something that we can do about this

**Comment by xndbogdan** [comment]
Wow that's a really strange one.
I'll definitely take a look at it.

**Comment by xndbogdan** [comment]
Hi I took a look at it but cannot replicate it.
Can you maybe attach a screenshot?
You can send it via mail if you want to.

**Comment by Oleafeon** [comment]
Hi 

this is what i get when i make a text white
![image](https://user-images.githubusercontent.com/20043831/195025793-e0fad75c-83b0-4e2b-a182-82028dbd7066.png)

When you select the tekst you can see that there is something
![image](https://user-images.githubusercontent.com/20043831/195025983-9f971603-0c9f-482e-aafa-268365fa4677.png)

as you can see here it add a color style element to the tekst with an important 
![image](https://user-images.githubusercontent.com/20043831/195026247-18c30313-413d-4338-8608-a5c4f1f0b4cd.png)

I cant overwrite this

**Comment by xndbogdan** [comment]
I see. Yeah, that's expected when making the text white, and I'm not sure how to fix it.
Do you have any suggestions?

**Comment by intrepidws** [comment]
I don't know if it's even possible but perhaps you could add a config variable to control the background color of the bard field itself?

**Comment by xndbogdan** [comment]
Sounds like a good idea, I'll try to make that happen

**Comment by xndbogdan** [comment]
Issue has been adressed, as of release 3.1
