### ISSUE TITLE
[3.1.1] Render view partial issue 

### ISSUE THREAD

**Issue by jeremyvienney** [xndbogdan/statamic-bard-text-color#22]
Hello,

I just upgrade Statamic to 3.4 and your package to 3.3.1.
And Statamic trigger an exception with this message : 
```Undefined property: stdClass::$key```

I have to remove the extension to render any view :(
I can provide you an access to my repo if you need.
Here is my shared debug flare : https://flareapp.io/share/B5Z8EDNP#F117

I think maybe there is an issue with some older text-color data where marks is not present or null.

Here is my app details :
```
Environment
Application Name: UserstoriesStudio
Laravel Version: 9.51.0
PHP Version: 8.1.12
Composer Version: 2.4.1
Environment: local
Debug Mode: ENABLED
URL: stories-studio.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.3 PRO

Statamic Addons
aryehraber/statamic-logbook: 2.1.0
jacksleight/statamic-bard-mutator: 2.0.1
jacksleight/statamic-bard-texstyle: 2.0.1
rias/statamic-position-fieldtype: 2.0.1
xndbogdan/statamic-bard-text-color: 3.1.1
```

**Comment by jeremyvienney** [comment]
I'm pretty sure that it is linked to old other marks type that is useless for me now, since it rely on bard addon which are not yet updated to 3.4.
Maybe the line 19 on TextColor.php ```'style' => $this->getTextColor($mark->attrs->key),``` should only get the key if type is 'textColor' ?

**Comment by xndbogdan** [comment]
I'll investigate. Thank you for reporting the issue!

**Comment by xndbogdan** [comment]
Hi!
Please update to 3.1.2 and confirm that the issue is fixed.
Thank you!
