### ISSUE TITLE
Error after updating to version 3.1.2

### ISSUE THREAD

**Issue by JoeriE** [xndbogdan/statamic-bard-text-color#24]
Hi,

I updated to the latest version (3.1.2) of the plugin to use it with Statamic 3.4, but I get several javascript errors:
![image](https://user-images.githubusercontent.com/11161180/218428046-644ab6bb-23f3-41a7-914a-4964efec9272.png)

The problem only occurs on existing bard fields with content. The content is hidden and nothing is clickable.
If I add a new field or add content to a existing field, there's no problem.

Best wishes,
Joeri

**Comment by xndbogdan** [comment]
Weird, I can't get it to happen. I'm gonna try and make a fix for it though.

**Comment by anakadote** [comment]
I'm experiencing the same issue, with the same JS errors in the console. The only "fix" is to completely remove the textColor marks from the content yaml.

**Comment by bernhardberger** [comment]
can confirm

**Comment by bernhardberger** [comment]
found the culprit:
https://github.com/xndbogdan/statamic-bard-text-color/pull/14/commits/60e6cf230a0c945e2236aa133c10b2f528f84aa4

here you rename the "color" attribute to "key". this breaks everything.

**Comment by bernhardberger** [comment]
and this: https://github.com/xndbogdan/statamic-bard-text-color/blob/main/resources/js/TextColor.js#L29 fails in the example above where there's an `!important` flag..

**Comment by bernhardberger** [comment]
PR added. this should fix the JS errors as it uses a proper js lib (tinycolor2) that can handle the color conversions properly.
