### ISSUE TITLE
Uninstalling `statamic-bard-text-color` without breaking existing YAML content?

### ISSUE THREAD

**Issue by bernhardberger** [xndbogdan/statamic-bard-text-color#27]
How do I properly remove the extension without breaking existing YAML content? I can't use 3.x because it breaks exising YAML content and I can't remove the addon alltogether because it breaks the BARD in the backend.

I'm trapped in hell. Please help me.

**Comment by heidkaemper** [comment]
I think this is a general Bard / TipTap problem and should be tackled by Statamic (or TipTap) itself.

Other addons that uses custom TipTap marks will likely have the same problem. These are just two of those addons:
https://github.com/new-data-services/statamic-bard-color-picker
https://github.com/OptimoApps/statamic-bard-text-align

You could switch from this addon to the Bard Color Picker plugin, which uses the 'color' attribute. But uninstalling that would cause the same problem.

It would be nice if Statamic Bard could just ignore marks that can't be rendered (anymore)..

**Comment by xndbogdan** [comment]
Hi!
Thank you both for contributing to this repo.
I wish I could've done more to address incoming issues with the package, but I've been way too busy lately.
I've merged @heidkaemper 's PR and will merge yours too. Right now it has conflicts. Either you fix them or I will fix them when I have the time.

Thanks again for contributing, I've added you to the readme as you've contributed to active development.
If you have any ideas on which direction to take this in and want to contribute faster/easier, I can gladly add you as contributors here, so you can make the experience of using this plugin a more pleasurable one.

Just let me know.
