### ISSUE TITLE
Bard disappeared after updating 

### ISSUE THREAD

**Issue by idaksh6** [xndbogdan/statamic-bard-text-color#29]
![image](https://user-images.githubusercontent.com/94969215/222627484-f2eeeb1d-4149-438c-bfb0-77162eb1c963.png)
![image](https://user-images.githubusercontent.com/94969215/222627508-afe54712-305a-4ace-8aec-5992d894a282.png)

**Comment by xndbogdan** [comment]
Does the issue still happen on 3.1.4?
