### ISSUE TITLE
bullet list not styled in the right color

### ISSUE THREAD

**Issue by Oleafeon** [xndbogdan/statamic-bard-text-color#31]
After implementing the plugin and placing a couple list's we found that there was a problem with the bullet colors.

Do you maybe have a fix for this, we need this on a relatively short term if possible.

Thanks in advance.

![image](https://user-images.githubusercontent.com/20043831/227142347-fbefcf2c-e86c-4f74-a93f-f89045f23dae.png)

**Comment by Oleafeon** [comment]
@xndbogdan do you have an idea?

**Comment by xndbogdan** [comment]
Hi. I'm not sure what could be causing the issue. I'll need to take a look & try to reproduce when I have the time.
I can only assume that it's got something to do with how I'm styling the elements.
