### ISSUE TITLE
Statamic 4 Compatibility

### ISSUE THREAD

**Issue by duncanmcclean** [xndbogdan/statamic-bard-text-color#32]
Hello 👋

Statamic 4 is due out any day now (in fact the [first beta release](https://github.com/statamic/cms/releases/tag/v4.0.0-beta.1) was tagged yesterday). 

We use this addon in a few of our projects and I was wondering if there was any plans to update this addon soon for compatibility with Statamic 4?

**Comment by xndbogdan** [comment]
Oh man, how time flies.
Sure, I'll update it to support v4.
I can't promise an exact timeline, seeing as I'm working on this in my free time, but I'll try my best.

**Comment by duncanmcclean** [comment]
No worries! Thanks for responding so quick.

**Comment by edinabazi** [comment]
@xndbogdan Would you be able to update this to work with Statamic 4 any time soon? We have a lot of pages that are broken due to this addon missing when we updated to Statamic 4. I wish I could myself help but I don't know any PHP unfortunately.

Thanks!

**Comment by xndbogdan** [comment]
I'm gonna make some times one of these days. Ideally at the beginning of the weekend. I'm gonna keep you updated for sure
