### ISSUE TITLE
Statamic 5 Compatibility

### ISSUE THREAD

**Issue by david-lobo** [xndbogdan/statamic-bard-text-color#34]
Hi,  

Thanks for the great addon.  We use this in our projects and i wanted to ask if you plan to do a Statamic 5 update?

Thanks
David

**Comment by xndbogdan** [comment]
Hi David,

Thank you for reaching out and for your kind words about the addon.

I appreciate you bringing the Statamic 5 compatibility issue to my attention.
I must admit that I haven't been keeping up with Statamic developments recently, so I wasn't even aware of the new version release.

Given the importance of ensuring compatibility for current users of Bard Text Color who may want to upgrade to Statamic 5, I will prioritize investigating the necessary changes this weekend.

I'll keep you posted on any progress regarding the Statamic 5 upgrade.
Thank you for your patience and understanding.

Best regards,
Bogdan

**Comment by xndbogdan** [comment]
Hi David,

Just a quick update: the Statamic 5 compatibility update took way less time than I was expecting. In fact, I've already released version 5 of the package. Please give it a try and let me know if it works as expected, or if you encounter any issues.

**Comment by xndbogdan** [comment]
I am assuming the plugin works as expected with Statamic 5, so I will close this issue.
