### ISSUE TITLE
Bard inside replicator making the titles stacked

### ISSUE THREAD

**Issue by pixelastronauts** [xndbogdan/statamic-bard-text-color#37]
Loving the addon, but I stumbled upon a problem when using your addon in combination with a replicator. 

After installing the titles are stacked: 

![screenshot](https://github.com/xndbogdan/statamic-bard-text-color/assets/77613333/cf7a3b74-1947-4be7-b66b-2d6615e80ee1)

After uninstalling, the styling is correct again.

I've already been searching for the problem, but can't seem to find it.

**Comment by xndbogdan** [comment]
I'll look into it. Thanks for reporting the issue.

**Comment by xndbogdan** [comment]
Hey.
I've looked into this issue but I am having a hard time replicating it - I assume I am doing something wrong.
<img width="901" alt="Screenshot 2024-06-17 at 04 23 54" src="https://github.com/xndbogdan/statamic-bard-text-color/assets/27998462/c6c5278b-d8a5-4f8d-94c4-449de1cda5b1">
Could you record a video of creating a blueprint with the replicators so I have a step by step guide on how to reproduce the issue and hopefully fix it?

**Comment by pixelastronauts** [comment]
<img width="1240" alt="Scherm­afbeelding 2024-06-19 om 15 58 44" src="https://github.com/xndbogdan/statamic-bard-text-color/assets/77613333/359b4423-59d7-48c6-9ba8-654226383b61">

It's this piece of Tailwind styling that offset's some styling. This is being added after installing the addon. 

I've figured it has something to do with the import `import '../css/tailwind.css'` inside of the  `resources/js/TextColorMenu.vue`

**Comment by xndbogdan** [comment]
Thanks for discovering this. I've disabled preflight and pushed a new version out (5.1.1).
Let me know if it works as expected now.

**Comment by pixelastronauts** [comment]
Worked like a charm!
