### ISSUE TITLE
FR: Add palette button only to specified fields

### ISSUE THREAD

**Issue by stuartcusackie** [xndbogdan/statamic-bard-text-color#6]
Just wondering if you have plans to allow the button to be applied to only specified bard fields. I'd rather not give the option on all of my bard fields.

Great work also. Thank you!

**Comment by xndbogdan** [comment]
Thank you for the suggestion.
I'll definitely look into it!

**Comment by xndbogdan** [comment]
It seems I have some free time now, so I can look into it.
Have you seen any plugins that can be applied only to specific bard fields?
If yes, then please link me to them so I can see how they did it and solve the issue faster 🚀

**Comment by stuartcusackie** [comment]
I'm afraid not. I'm really only getting into Statamic lately. Will post if I find something useful.

**Comment by xndbogdan** [comment]
Hi. As soon as tiptap 2 gets added to statamic, I'm pulling this branch to master & launching a new version.
It should also fix this issue.
https://github.com/xndbogdan/statamic-bard-text-color/tree/feature/update-tiptap

**Comment by xndbogdan** [comment]
I wanted to fix it earlier so I released v2.3.
Please update the dependency.
You should now be able to disable this field.

**Comment by stuartcusackie** [comment]
Thank you. I will try this again in the future.
