### ISSUE TITLE
Can not be disabled

### ISSUE THREAD

**Issue by LorensoD** [xndbogdan/statamic-bard-text-color#9]
When the text color is disabled in the blue print it is still showing up when editing.

Blueprint:
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/25841435/162470855-bde17e6c-566d-4cdc-b189-825dc091e392.png">

When editing:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/25841435/162471034-9866929b-45e2-4ed5-bd65-b465c768c1dc.png">

It also stores text color data when I didn't specifically set this.

**Comment by xndbogdan** [comment]
I got some time this weekend.
Will work on a fix :)

**Comment by xndbogdan** [comment]
Hi. As soon as tiptap 2 gets added to statamic, I'm pulling this branch to master & launching a new version.
It should also fix this issue.
https://github.com/xndbogdan/statamic-bard-text-color/tree/feature/update-tiptap

**Comment by LorensoD** [comment]
Awesome! 🙌 Much appreciated.

**Comment by xndbogdan** [comment]
Fixed. Please update dependency to version 2.3.
Have a good one!
